vive-only:
  enabled: true
  kickmessage: You need to have the Vive Mod installed to join this server!
  waittime: 20
permissions:
  vivegroup: vive.vivegroup
  non-vivegroup: vive.non-vivegroup
  freemovegroup: vive.freemovegroup
