vive-only: false
vive-only.kickmessage: This server is configured for Vivecraft players only.
vive-only.waittime: 60
permissions.vivegroup: 'vive.vivegroup'
permissions.non-vivegroup: 'vive.non-vivegroup'
permissions.freemovegroup: 'vive.freemovegroup'

