name: Vivecraft Spigot Extensions
version: '1.10.2 r1'
main: org.vivecraft.VSE
depend:
- ProtocolLib
softdepend:
- Vault
dev-url: http://www.vivecraft.org/
commands:
  vive:
    description: 'Vivecraft Spigot Plugin: Limit to Vive-Players. Per Client Permissions, Prefixes and more.'
    usage: /<command> - displays Vivecraft Spigot-Help
    permission: minevive.command
permissions:
  minevive.config:
    default: op
    description: Allows changing plugin configuration ingame via commands
  minevive.command:
    default: op
    description: |-
      Needed for any player that want's to use the /vive-command. If not granted, the user shouldn't
      see the command in /help.
